server:
  port: 8120
spring:
  application:
    name: client-admin
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springbootTest?characterEncoding=utf-8
      userName: root
      password: 123456789
    #html
  mvc:
      view:
        prefix: /
        suffix: .html
  thymeleaf:
      prefix: classpath:/templates/
  resource:
    path: /upload/
    path.pattern: /upload/**
    folder:
      windows: G:/upload
      linux: /upload/
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8100/eureka/