server:
  port: 8110
spring:
  application:
    name: client-account
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootTest?characterEncoding=utf-8
    userName: root
    password: 123456789
    #jpa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: true
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8100/eureka/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.zyq.account.mapper